title: "Marius Michel"
email: "kontakt@marius-michel.de"
description: "Langeweile in prärevolutionären Zeiten..."

lang: "de"
timezone: "Europe/Berlin"
markdown: "kramdown"
future: true

collections:
  entries:
    output: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
